### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by dumblob** [Rustixir/blackbird#14]
I wonder whether darkbird supports or plans to support transactions.

If so, what kind of transactions (involved keys/data fully known before transactions begins; involved keys/data being discovered first during transaction; read-only transactions for better utilization; read-write transactions; non-starving acceptance of transactions; nested transactions; distributed transactions yes or not; ...)?

**Comment by Rustixir** [comment]
Yes, I have a plan to implement it very soon.
 I will think about it this weekend, but I don't have any plans now

**Comment by dumblob** [comment]
Nice, sounds encouraging!

Feel free to write down your thoughts here first so that others can read and perhaps react to them :wink:. Thanks!

**Comment by Rustixir** [comment]
Yes sure !! 😊

**Comment by Rustixir** [comment]
Darkbird is built for ultra-fast searches for real-time applications
After a lot of thinking,
transaction is not really in our target.

**Comment by dumblob** [comment]
Hm, ok. It is a pity but yeah, product management is product management :wink:.

Closing for lack of actionable items.
