### ISSUE TITLE
Error when using version from crates.io

### ISSUE THREAD

**Issue by IgnisDa** [Rustixir/blackbird#19]
Thanks for this project! I would like to try this project in mine, but I get this error:

![image](https://github.com/Rustixir/darkbird/assets/60938164/71973139-cae4-40cc-9a4f-ee8586217f8b)

It works fine if I set it as a git dependency.
Maybe the version on crates.io is not updated to the latest?

**Comment by Rustixir** [comment]
Thanks for your reports

**Comment by IgnisDa** [comment]
@Rustixir Would it be possible for you to update it?

**Comment by Rustixir** [comment]
sorry i was to much busy, but i fixed it now
