### ISSUE TITLE
`Incorrect cast in anymap`

### ISSUE THREAD

**Issue by IgnisDa** [Rustixir/blackbird#20]
While using this project, I got this security vulnerability report:
![image](https://github.com/Rustixir/darkbird/assets/60938164/f712bd45-0434-410b-aa7a-02de2f59987e)

Here is the dependency tree:
![image](https://github.com/Rustixir/darkbird/assets/60938164/34e0fe6c-69c0-4bde-89a2-c556b39b0e19)

**Comment by Rustixir** [comment]
Thanks for your report . Its correct but we aren't using conversation u64 with *u64
